source "https://rubygems.org"

gem 'sinatra', '~> 1.4.7'
gem 'sinatra-contrib', '~> 1.4.7'
gem 'sinatra-activerecord', '~> 2.0', '>= 2.0.9'
gem 'sqlite3', '~> 1.3', '>= 1.3.11'
gem 'rake', '~> 10.4', '>= 10.4.2'
gem 'twitter', '~> 5.16.0'
gem 'rufus-scheduler', '~> 3.2.1'